project_id = "rfgeckzjtbkqoijxwltm"

[functions.occurrence-ai]
verify_jwt = true

[functions.report-occurrence-ai]
verify_jwt = false

[functions.occurrence-ai-recommendations]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.seed-demo-data]
verify_jwt = true

[functions.seed-demo-users]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.sigaflo-chat]
verify_jwt = true
