import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Loader2, X } from 'lucide-react';
import { useForestOperators, useCreateLicense, useUpdateLicense, type ForestLicense } from '@/hooks/useForestry';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';

const formSchema = z.object({
  license_type: z.enum(['exploitation', 'transport', 'export', 'sawmill', 'processing']),
  operator_id: z.string().min(1, 'Operador é obrigatório'),
  concession_area_name: z.string().optional(),
  concession_area_ha: z.coerce.number().min(0, 'O valor deve ser positivo').optional(),
  province_id: z.string().optional(),
  municipality_id: z.string().optional(),
  latitude: z.coerce.number().min(-90, 'Latitude inválida (-90 a 90)').max(90, 'Latitude inválida (-90 a 90)').optional(),
  longitude: z.coerce.number().min(-180, 'Longitude inválida (-180 a 180)').max(180, 'Longitude inválida (-180 a 180)').optional(),
  authorized_species: z.string().optional(),
  authorized_volume_m3: z.coerce.number().min(0, 'O valor deve ser positivo').optional(),
  start_date: z.string().optional(),
  expiry_date: z.string().optional(),
  license_fee_aoa: z.coerce.number().optional(),
  notes: z.string().optional(),
});

type FormData = z.infer<typeof formSchema>;

interface LicenseFormProps {
  open: boolean;
  onClose: () => void;
  license?: ForestLicense | null;
}

export function LicenseForm({ open, onClose, license }: LicenseFormProps) {
  const { data: operators } = useForestOperators();
  const { data: provinces } = useQuery({
    queryKey: ['provinces'],
    queryFn: async () => {
      const { data, error } = await supabase.from('provinces').select('*').order('name');
      if (error) throw error;
      return data;
    },
  });

  const createLicense = useCreateLicense();
  const updateLicense = useUpdateLicense();

  const form = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      license_type: 'exploitation',
      operator_id: '',
      concession_area_name: '',
      concession_area_ha: undefined,
      province_id: '',
      authorized_species: '',
      authorized_volume_m3: undefined,
      start_date: '',
      expiry_date: '',
      license_fee_aoa: undefined,
      notes: '',
    },
  });

  useEffect(() => {
    if (license) {
      form.reset({
        license_type: license.license_type,
        operator_id: license.operator_id,
        concession_area_name: license.concession_area_name || '',
        concession_area_ha: license.concession_area_ha || undefined,
        province_id: license.province_id || '',
        latitude: license.latitude || undefined,
        longitude: license.longitude || undefined,
        authorized_species: license.authorized_species?.join(', ') || '',
        authorized_volume_m3: license.authorized_volume_m3 || undefined,
        start_date: license.start_date || '',
        expiry_date: license.expiry_date || '',
        license_fee_aoa: license.license_fee_aoa || undefined,
        notes: license.notes || '',
      });
    } else {
      form.reset({
        license_type: 'exploitation',
        operator_id: '',
        concession_area_name: '',
        province_id: '',
        authorized_species: '',
        notes: '',
      });
    }
  }, [license, form]);

  const onSubmit = async (data: FormData) => {
    const basePayload = {
      license_type: data.license_type,
      operator_id: data.operator_id,
      concession_area_name: data.concession_area_name || null,
      concession_area_ha: data.concession_area_ha || null,
      province_id: data.province_id || null,
      municipality_id: data.municipality_id || null,
      latitude: data.latitude || null,
      longitude: data.longitude || null,
      authorized_species: data.authorized_species
        ? data.authorized_species.split(',').map((s) => s.trim()).filter(Boolean)
        : [],
      authorized_volume_m3: data.authorized_volume_m3 || null,
      start_date: data.start_date || null,
      expiry_date: data.expiry_date || null,
      license_fee_aoa: data.license_fee_aoa || null,
      notes: data.notes || null,
    };

    if (license) {
      await updateLicense.mutateAsync({ id: license.id, ...basePayload });
    } else {
      // license_number is auto-generated by trigger
      await createLicense.mutateAsync({ 
        ...basePayload, 
        license_number: '' // Will be overwritten by trigger
      } as any);
    }
    onClose();
  };

  const isLoading = createLicense.isPending || updateLicense.isPending;

  return (
    <Dialog open={open} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{license ? 'Editar Licença' : 'Nova Licença Florestal'}</DialogTitle>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <div className="grid gap-4 sm:grid-cols-2">
              <FormField
                control={form.control}
                name="license_type"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Tipo de Licença *</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Seleccione o tipo" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="exploitation">Exploração</SelectItem>
                        <SelectItem value="transport">Transporte</SelectItem>
                        <SelectItem value="export">Exportação</SelectItem>
                        <SelectItem value="sawmill">Serraria</SelectItem>
                        <SelectItem value="processing">Transformação</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="operator_id"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Operador *</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Seleccione o operador" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {operators?.map((op) => (
                          <SelectItem key={op.id} value={op.id}>
                            {op.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <FormField
                control={form.control}
                name="concession_area_name"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Nome da Área de Concessão</FormLabel>
                    <FormControl>
                      <Input {...field} placeholder="Ex: Floresta do Mayombe" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="concession_area_ha"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Área (ha)</FormLabel>
                    <FormControl>
                      <Input {...field} type="number" placeholder="0" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <FormField
                control={form.control}
                name="province_id"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Província</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Seleccione a província" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {provinces?.map((prov) => (
                          <SelectItem key={prov.id} value={prov.id}>
                            {prov.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="authorized_volume_m3"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Volume Autorizado (m³)</FormLabel>
                    <FormControl>
                      <Input {...field} type="number" placeholder="0" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="authorized_species"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Espécies Autorizadas</FormLabel>
                  <FormControl>
                    <Input {...field} placeholder="Separadas por vírgula: Pau-ferro, Mukula, Ébano" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="grid gap-4 sm:grid-cols-2">
              <FormField
                control={form.control}
                name="start_date"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Data de Início</FormLabel>
                    <FormControl>
                      <Input {...field} type="date" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="expiry_date"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Data de Expiração</FormLabel>
                    <FormControl>
                      <Input {...field} type="date" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="license_fee_aoa"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Taxa de Licenciamento (AOA)</FormLabel>
                  <FormControl>
                    <Input {...field} type="number" placeholder="0" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="notes"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Observações</FormLabel>
                  <FormControl>
                    <Textarea {...field} rows={3} placeholder="Notas adicionais..." />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="flex justify-end gap-3">
              <Button type="button" variant="outline" onClick={onClose}>
                Cancelar
              </Button>
              <Button type="submit" disabled={isLoading}>
                {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                {license ? 'Guardar Alterações' : 'Criar Licença'}
              </Button>
            </div>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
