import { Helmet } from "react-helmet-async";
import { useLocation } from "react-router-dom";
import {
  buildDynamicOgImage,
  inferSectorFromPath,
  resolveStaticOgImage,
  type OgSector,
} from "@/lib/seo/ogImageRegistry";

export interface SeoHeadProps {
  title: string;
  description: string;
  /** Path-relative URL for canonical (e.g. "/portal/agricultura"). */
  path: string;
  /** Imported asset URL (image src). Will be resolved to absolute. Overrides registry & dynamic. */
  image?: string;
  imageAlt?: string;
  /** When true (or providing dynamic options) generate an SVG card via the og-image edge function. */
  dynamic?:
    | boolean
    | {
        title?: string;
        subtitle?: string;
        sector?: OgSector;
      };
  type?: "website" | "article";
}

const SITE = "https://sigaflo.lovable.app";
const SITE_NAME = "SIGAFLO — Portal Público";

function absolutize(url?: string) {
  if (!url) return undefined;
  if (/^https?:\/\//i.test(url)) return url;
  try {
    return new URL(url, SITE).toString();
  } catch {
    return undefined;
  }
}

const DEFAULT_OG_IMAGE = `${SITE}/og-image.png`;

/**
 * Resolution order for og:image:
 *   1. Explicit `image` prop (page-level static asset, e.g. sector hero).
 *   2. `dynamic` prop → SVG generated by edge function.
 *   3. Registry static image for the current pathname.
 *   4. Global fallback /og-image.png.
 */
export function SeoHead({
  title,
  description,
  path,
  image,
  imageAlt,
  dynamic,
  type = "website",
}: SeoHeadProps) {
  const url = `${SITE}${path.startsWith("/") ? path : `/${path}`}`;
  const location = useLocation();
  const currentPath = location?.pathname || path;

  let resolvedImage: string | undefined = absolutize(image);
  let isSvg = false;

  if (!resolvedImage && dynamic) {
    const opts = typeof dynamic === "object" ? dynamic : {};
    resolvedImage = buildDynamicOgImage({
      title: opts.title ?? title,
      subtitle: opts.subtitle ?? description,
      sector: opts.sector ?? inferSectorFromPath(currentPath),
    });
    isSvg = true;
  }

  if (!resolvedImage) {
    const registry = resolveStaticOgImage(currentPath);
    if (registry) resolvedImage = absolutize(registry);
  }

  const ogImage = resolvedImage ?? DEFAULT_OG_IMAGE;

  return (
    <Helmet>
      <title>{title}</title>
      <meta name="description" content={description} />
      <link rel="canonical" href={url} />

      {/* Open Graph */}
      <meta property="og:site_name" content={SITE_NAME} />
      <meta property="og:type" content={type} />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:url" content={url} />
      <meta property="og:locale" content="pt_AO" />
      <meta property="og:image" content={ogImage} />
      {isSvg && <meta property="og:image:type" content="image/svg+xml" />}
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      {imageAlt && <meta property="og:image:alt" content={imageAlt} />}

      {/* Twitter Card */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={ogImage} />
      {imageAlt && <meta name="twitter:image:alt" content={imageAlt} />}
    </Helmet>
  );
}
